name: ateam

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/testing-farm/tmt:1.6.0
    env:
      RUN_DIR: /var/tmp/tmt/$GITHUB_RUN_ID-$GITHUB_RUN_NUMBER

    steps:
      - uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p -m 700 ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Image build
        run: |
            rm -rf $RUN_DIR
            tmt run -vvv --all -i $RUN_DIR \
                provision --how connect --user centos --guest ${{ secrets.HOST }} --key ~/.ssh/id_rsa
        shell: bash
