name: ateam

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    # We accept only one job for now, ostree.sh cannot do parallel builds
    concurrency: single
    runs-on: ubuntu-latest
    container: quay.io/testing-farm/tmt:1.6.0
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2

      - name: Create SSH key
        run: |
          mkdir -p -m 700 ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Image build
        run: |
            tmt run -vvv --all provision --how connect --guest ${{ secrets.HOST }} --key ~/.ssh/id_rsa
        shell: bash
